<?php

namespace HeticBundle\Repository;

use \Doctrine\ORM\EntityRepository;
/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    public function findAllStudentByDate()
    {
        return $this
            ->getEntityManager()
            ->createQuery('SELECT s FROM HeticBundle:Student s ORDER BY s.dateOfBirth DESC')
            ->getResult()
            ;
    }
}
